name: Build LaTeX document
on: 
  [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: 00main.tex
          working_directory: LaTeX
      - name: Push to draft branch
        if: success()
        run: git checkout -b draft && git add LaTeX/00main.pdf && git commit -m "Add new draft" && git push origin draft
