name: Build LaTeX document
on: 
  [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: 00main.tex
          working_directory: LaTeX
      - name: Create release
        if: success()
        uses: ncipollo/release-action@v1
        with:
          tag: "latest"
          artifacts: "LaTeX/00main.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
