name: Build LaTeX document
on: 
  push:
    tags:
    - '*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: 00main.tex
          working_directory: LaTeX
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: draft 
          path: LaTeX/00main.pdf
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "draft.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
